/**
 * binary-format.js
 *
 * Resolves byte offsets for a format list that was generated by
 * ExportParamsJson.m.  No padding re-computation is needed here because
 * MATLAB already encoded all junk/padding entries in the JSON.
 */

/**
 * Byte size per single element for a given type name.
 * Matches TypeSize.m exactly; unknown types default to 4 (enum / int32).
 * @param {string} type
 * @returns {number}
 */
export function typeSize(type) {
    switch (type) {
        case 'double': case 'int64':  case 'uint64':  return 8;
        case 'single': case 'int32':  case 'uint32':  return 4;
        case 'int16':  case 'uint16':                 return 2;
        case 'int8':   case 'uint8':
        case 'logical': case 'boolean':               return 1;
        default:                                       return 4; // enum / unknown
    }
}

/**
 * Normalise a dims value from the JSON to a [rows, cols] pair.
 * MATLAB may store scalar dims as a single-element array (e.g. [3] for a
 * 1-D array of 3 elements); we treat that as [3, 1].
 * @param {number|number[]} dims
 * @returns {[number, number]}
 */
export function normalizeDims(dims) {
    if (!Array.isArray(dims) || dims.length === 0) return [1, 1];
    if (dims.length === 1)                          return [dims[0], 1];
    return [dims[0], dims[1]];
}

/**
 * Total number of scalar elements in a format entry.
 * @param {Object} entry
 * @returns {number}
 */
export function elemCount(entry) {
    if (entry.isJunk) return entry.elemCount;
    const [r, c] = normalizeDims(entry.dims);
    return r * c;
}

/**
 * Total byte footprint of a single format entry.
 * @param {Object} entry
 * @returns {number}
 */
export function entryBytes(entry) {
    if (entry.isJunk) return entry.elemCount; // each junk byte is uint8
    const [r, c] = normalizeDims(entry.dims);
    return r * c * typeSize(entry.type);
}

/**
 * Walk the format list in order and attach a byteOffset to each entry.
 * Returns a new array; the original is not mutated.
 * @param {Object[]} formatList
 * @returns {Object[]}
 */
export function resolveOffsets(formatList) {
    let offset = 0;
    return formatList.map(entry => {
        const enriched = { ...entry, byteOffset: offset };
        offset += entryBytes(entry);
        return enriched;
    });
}

/**
 * Sum of all entry byte sizes – i.e. the expected .dat file size.
 * @param {Object[]} formatList
 * @returns {number}
 */
export function totalBytes(formatList) {
    return formatList.reduce((acc, e) => acc + entryBytes(e), 0);
}
